branches:
  only:
  - dev
  - /^(release|hotfix)\/.*$/
  - master
matrix:
  include:
  - name: "kjnet"
    language: node_js
    node_js:
    - 16
    cache:
      directories:
      - node_modules
    branches:
      only:
      - dev
    script:
    - npm install
    - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then npm run build:dev; fi
    - if [[ "$TRAVIS_BRANCH" =~ ^(release|hotfix)\/.*$ ]]; then npm run build:prod; fi
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi
    deploy:
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/* kj767@dream.bykev.in:/home/kj767/kevinjoseph.net;
        rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/.htaccess kj767@dream.bykev.in:/home/kj767/kevinjoseph.net;
        fi
      on:
        branch: master
    before_install:
    - openssl aes-256-cbc -K $encrypted_adb1fe1c85a4_key -iv $encrypted_adb1fe1c85a4_iv
      -in travis_rsa.enc -out /tmp/travis_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_rsa
    - ssh-add /tmp/travis_rsa
    addons:
      ssh_known_hosts: dream.bykev.in
