<h2>Contact Information</h2>
<dl class="clearAfter">
<dt>E-mail</dt>
<dd>kevin.p.joseph@gmail.com</dd>
<dt>Phone</dt>
<dd>+1 612-597-2426</dd>
<dt>Postal Address</dt>
<dd>8355 Station Village Ln<br />Unit 4103<br />San Diego CA 92108<br />United States</dd>
<dt>Skype</dt>
<dd>kevin.p.joseph</dd>
</dl>
<p>E-mail is, by far, the best method for contacting me.  Should you call, please leave a message, and I will return your call when my schedule allows; during the work day, it will likely take some time for me to get away for a phone call.</p>
<p>Please be aware that San Diego is in the North American Pacific Time Zone (GMT -8).</p>
