<h2>Professional Development Examples</h2>
<p>Unfortunately, I've not done a good job of collecting code samples from previous employment before those sites disappear; such is the volatile nature of the Internet, it seems.  I can point to a few simple examples of previous work, but most of the more in-depth examples are no longer available.</p>
<ul class="resume">
	<li>
		Turbine Store: <a href="http://store.turbine.com/store/turbine/en_US/list/categoryID.58516100/themeid.29252200" target="_blank">DDO</a> and <a href="http://store.turbine.com/store/turbine/en_US/list/categoryID.58516200/themeid.28979900" target="_blank">LOTRO</a>
		<p>Developed 2012 at Digital River</p>
		<p>This was a project to redesign their site.  The client has two main products, and wanted those categories to appear as two separate sites.</p>
		<p>Features:</p>
		<ul>
			<li>Slideshow rotators on home and category pages for client-created offers</li>
			<li>Custom jQuery plugin (<a href="/files/jquery-resizeImages.js.txt" target="_blank">code</a>) for image resizing for product images, as the client did not supply images with a standard size</li>
		</ul>
	</li>
	<li>
		<a href="http://www.buyfcpa.com/store/fujitsu/en_US/pd/ThemeID.16225600/productID.263844900/" target="_blank">Fujitsu store</a>
		<p>This was a project to implement a third-party review system, BazaarVoice, via a combination of their API and internal AJAX calls.</p>
	</li>
		
</ul>