<h2>External Profiles</h2>
<p>Like many people, I have profiles on job search and other related sites:</p>
<ul>
	<li><a href="http://www.beknown.com/kjoseph" target="_blank">Monster.com (BeKnown profile)</li>
	<li><a href="http://www.linkedin.com/in/kjjoseph" target="_blank">LinkedIn profile</li>
	<li><a href="http://www.careerbuilder.com/" target="_blank">CareerBuilder</li>
	<li><a href="https://codefights.com/profile/-kj" target="_blank">CodeFights</li>
	<li><a href="http://www.careerone.com.au/" target="_blank">CareerOne</li>
	<li><a href="http://www.dice.com/" target="_blank">Dice</li>
	<li><a href="https://www.seek.com.au" target="_blank">Seek</li>
</ul>
