<h2>Profile</h2>
<p>My name, as you may have already seen, is Kevin Joseph.  I'm an experienced front-end web developer with ten years of professional experience as a developer.  I'm currently located in San Diego, California, in the United States. This online profile/resume has been created mainly as a reference for those who may be interested in hiring me; it contains information about my professional and personal experience in the web development field.</p>
<h2>Objective</h2>
<p>I am currently looking for a new position.  Ideally I would like to stay in the San Diego area, but am open to the right opportunity elsewhere.  I prefer full-time positions, but will consider contracts as well.</p>
