<h2>Personal Development Examples</h2>
<p>Outside of work hours, I do often work on personal projects, in order to keep up my skills.  I've created a <a href="https://github.com/kj-joseph/" target="_blank">github account</a> to showcase the code used during some of my recent projects:</p>
<ul class="resume">
	<li>
		<a href="http://www.kevinjoseph.net/">KevinJoseph.net</a>
		<p>The site you're viewing.  Updated in June 2015 to utilize a new technology stack centered around AngularJS.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="http://angularjs.org/" target="_blank">AngularJS</a></li>
			<li><a href="http://sass-lang.com" target="_blank">Sass</a></li>
			<li><a href="http://getbootstrap.com/" target="_blank">Bootstrap</a></li>
			<li><a href="http://modernizr.com/" target="_blank">Modernizr</a></li>
			<li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
			<li><a href="http://nodejs.org/" target="_blank">Node.js</a></li>
			<li><a href="http://bower.io" target="_blank">Bower</a></li>
			<li><a href="http://gulpjs.com/" target="_blank">Gulp</a></li>
			<li><a href="http://karma-runner.github.io/" target="_blank">Karma</a></li>
			<li><a href="http://phantomjs.org" target="_blank">PhantomJS</a></li>
			<li><a href="http://jasmine.github.io" target="_blank">Jasmine</a></li>
			<li><a href="http://github.com/gotwarlost/istanbul" target="_blank">Istanbul</a></li>
		</ul>
	</li>
	<li>
		<a href="http://www.kjbranded.com/" target="_blank">KJ Branded</a>
		<p>My graphic design side business.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="https://reactjs.org/" target="_blank">React<a></li>
			<li><a href="https://webpack.js.org/" target="_blank">Webpack<a></li>
			<li><a href="https://babeljs.io/" target="_blank">Babel<a></li>
			<li><a href="https://sass-lang.com/" target="_blank">Sass<a></li>
		</ul>
</li>
	<li>
		<a href="http://www.supportyourlocalclub.com/" target="_blank">Support Your Local Club</a>
		<p>A site for locating local professional and semi-pro soccer teams in the United States and Canada.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="http://ellislab.com/codeigniter" target="_blank">CodeIgniter</a></li>
			<li><a href="http://www.php.net/" target="_blank">PHP</a></li>
			<li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
			<li><a href="http://wordpress.org/" target="_blank">WordPress</a></li>
			<li><a href="https://developers.google.com/maps/documentation/javascript/" target="_blank">Google Maps JavaScript API</a></li>
		</ul>
	</li>
		
</ul>
