<h2>Contact Information</h2>
<dl class="clearAfter">
<dt>E-mail</dt>
<dd>kevin.p.joseph@gmail.com</dd>
<dt>Phone</dt>
<dd>+1 612-597-2426</dd>
<dt>Postal Address</dt>
<dd>3208 Park Ave<br />Minneapolis MN 55407<br />United States</dd>
</dl>
<p>E-mail is, by far, the best method for contacting me.  Should you call, please leave a message, and I will return your call when my schedule allows; during the work day, it will likely take some time for me to get away for a phone call.</p>
<p>Please be aware that Minneapolis is in the North American Central Time Zone (GMT -6).</p>