<h2>Employment History</h2>
<ul class="resume">
	<li>Best Buy &#8211; Richfield, Minnesota <p>Web Developer, September 2013 - present (contract)</p>
		<ul>
			<li>Implement Adobe SiteCatalyst tracking solutions using JavaScript</li>
			<li>Contributed to complete code overhaul using Require.js</li>
			<li>Integrated use of Signal Tag Manager into new framework</li>
			<li>Working to implement unit testing on new framework</li>
		</ul>
	</li>
	<li>Target &#8211; Minneapolis, Minnesota <p>Web Developer, June 2013 - September 2013 (contract)</p>
		<ul>
			<li>Enhanced and supported iGuide, a web portal for students built on Liferay</li>
			<li>UI development using HTML, CSS, JSP, JavaScript / jQuery, and AJAX / JSON</li>
		</ul>
	</li>
	<li>Capella University &#8211; Minneapolis, Minnesota <p>Web Developer, January 2013 - March 2013 (contract)</p>
		<ul>
			<li>Enhancements and support on iGuide, a web application portal built on Liferay</li>
			<li>UI development using HTML4/5, CSS2/3, JSP, AJAX/JSON, Javascript/jQuery</li>
		</ul>
	</li>
	<li>Ambient Consulting &#8211; Minneapolis, Minnesota <p>Web Developer, September 2012 - November 2012</p>
		<ul>
			<li>Part of development team for Preventice, developing web applications for medical industry</li>
			<li>UI development using HTML, CSS, JSP, JavaScript / jQuery / Dojo, and AJAX / JSON</li>
		</ul>
	</li>
	<li>Digital River &#8211; Minnetonka, Minnesota <p>Web Developer, February 2011 - present</p>
		<ul>
			<li>Customized and maintained customer e-commerce sites</li>
			<li>UI development using HTML, CSS, JSP, JavaScript / jQuery, and AJAX / JSON</li>
			<li>Developed UI for THQ store redesign, including working with integration team to implement single sign-on</li>
		</ul>
	</li>
	<li>Internet Broadcasting &#8211; St. Paul, Minnesota <p>Web Developer, January 2008 - February 2011</p>
		<ul>
			<li>Maintained and enhanced media customer websites, specializing in television station sites</li>
			<li>UI development using HTML, CSS, XSLT, JavaScript / YUI, and AJAX / JSON</li>
			<li>Lead developer for Cox Media sites</li>
			<li>Implemented Adobe SiteCatalyst tracking code on Cox Media sites</li>
		</ul>
	</li>
</ul>
