<h2>Employment History</h2>
<ul class="resume">
	<li>Best Buy <em>(contract assignment)</em> &#8211; Richfield, Minnesota <p>Web Developer, September 2013 - present</p>
		<ul>
			<li>Implement Adobe SiteCatalyst (Omniture) tracking solutions using javascript</li>
		</ul>
	</li>
	<li>Target <em>(contract assignment)</em> &#8211; Minneapolis, Minnesota <p>Web Developer, June 2013 - September 2013</p>
		<ul>
			<li>Outline and implement Adobe SiteCatalyst (Omniture) tracking tags using Ensighten Tag Manager</li>
		</ul>
	</li>
	<li>Capella University <em>(contract assignment)</em> &#8211; Minneapolis, Minnesota <p>Web Developer, January 2013 - March 2013</p>
		<ul>
			<li>Enhancements and support on iGuide, a web application portal built on Liferay</li>
			<li>UI development using HTML4/5, CSS2/3, JSP, AJAX/JSON, Javascript/jQuery</li>
		</ul>
	</li>
	<li>Ambient Consulting &#8211; Minneapolis, Minnesota <p>Web Developer, September 2012 - November 2012</p>
		<ul>
			<li>Part of a development team for Preventice, developing web applications for the medical industry</li>
			<li>UI development using HTML4/5, CSS2/3, JSP, AJAX/JSON, Javascript/jQuery/Dojo</li>
		</ul>
	</li>
	<li>Digital River &#8211; Minnetonka, Minnesota <p>Web Developer, February 2011 - present</p>
		<ul>
			<li>Customized and maintained customer e-commerce websites using a variety of methods: HTML/XHTML/CSS, Javascript/jQuery, AJAX/JSON, JSP</li>
		</ul>
	</li>
	<li>Internet Broadcasting &#8211; St. Paul, Minnesota <p>Web Developer, January 2008 - February 2011</p>
		<ul>
			<li>Maintained/enhanced media customer websites using a variety of methods: internal CMS, HTML/XHTML/CSS, Javascript, XSLT</li>
		</ul>
	</li>
	<li>Thomson FindLaw &#8211; Eagan, Minnesota <p>Web Developer, May 2005 - November 2007</p>
		<ul>
			<li>Created HTML/CSS web site templates from Photoshop documents, coordinating with designer to achieve positive results.</li>
			<li>Created Flash animations for FirmSite web products.</li>
		</ul>
	</li>
</ul>
