<h2>Skill Sets</h2>
<p>This is a listing of web and web-related technologies I have used professionally and personally.</p>
<ul>
	<li>Basic Web
		<ul>
			<li>HTML 4/5</li>
			<li>CSS 2/3</li>
			<li>XHTML</li>
		</ul>
	</li>
	<li>Client-side scripting
		<ul>
			<li>Javascript</li>
			<li>jQuery</li>
			<li>AJAX</li>
			<li>JSON</li>
			<li>XML</li>
			<li>Backbone.js</li>
			<li>Underscore.js</li>
			<li>Require.js</li>
			<li>Handlebars</li>
			<li>YUI</li>
		</ul>
	</li>
	<li>Server-side
		<ul>
			<li>PHP</li>
			<li>CodeIgniter</li>
			<li>JSP</li>
			<li>XSLT</li>
			<li>MySQL</li>
		</ul>
	</li>
	<li>Design Software
		<ul>
			<li>Adobe Photoshop</li>
			<li>Adobe Illustrator</li>
		</ul>
	</li>
	<li>Source Control
		<ul>
			<li>SVN</li>
			<li>git</li>
			<li>GitHub</li>
			<li>Atlassian SourceTree</li>
			<li>GitTools</li>
		</ul>
	</li>
	<li>Debugging
		<ul>
			<li>Charles Proxy</li>
			<li>Firebug</li>
			<li>Chrome Developer Tools</li>
			<li>Internet Explorer Developer Tools</li>
		</ul>
	</li>
	<li>Operating Systems
		<ul>
			<li>Windows</li>
			<li>Linux</li>
			<li>Mac OS X</li>
		</ul>
	</li>
	<li>Development Environments / Buildilng
		<ul>
			<li>Eclipse</li>
			<li>IntelliJ IDEA</li>
			<li>Maven</li>
			<li>Tomcat</li>
			<li>Ant</li>
		</ul>
	</li>
	<li>APIs / CMS
		<ul>
			<li>Google Maps API v3</li>
		</ul>
	</li>
	<li>Content Management
		<ul>
			<li>Wordpress</li>
		</ul>
	</li>
</ul>
