<h2>Profile</h2>
<p>My name, as you may have already seen, is Kevin Joseph.  I'm an experienced front-end web developer with ten years of professional experience as a developer.  I'm currently located in Minneapolis, Minnesota, in the United States. This online profile/resume has been created mainly as a reference for those who may be interested in hiring me; it contains information about my professional and external experience in the web development field.</p>
<h2>Objective</h2>
<p>While I now live in the Twin Cities area, my current objective is to find a position in another location; specifically, I'm looking to relocate to the American West Coast (more specifically San Diego, San Francisco/San Jose, or Los Angeles) or Melbourne, Australia</p>
<p>You may ask: "Kevin, why are you looking to relocate?"  I've lived in the Midwestern U.S. my entire life; it's time for a change, especially from a weather standpoint.  While I would like to relocate to one of those places quickly, I definitely prefer having employment waiting before picking up and moving a long distance.</p>
<p>I prefer direct, full-time positions; I will, however, consider reasonable contracts.</p>
