<h2>Personal Development Examples</h2>
<p>Outside of work hours, I do often work on personal projects, in order to keep up my skills.  I've created a <a href="https://github.com/kj-joseph/" target="_blank">github account</a> to showcase the code used during some of my recent projects:</p>
<ul class="resume">
	<li>
		<a href="http://ifa.bykev.in/" target="_blank">IFA</a>
		<p>A prototype website for a soccer fantasy league.  This is definitely a work in progress, in the hopes of being fully ready for the 2014-15 season.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="http://backbonejs.org/" target="_blank">backbone.js</a></li>
			<li><a href="http://underscorejs.org/" target="_blank">underscore.js</a></li>
			<li><a href="http://modernizr.com/" target="_blank">Modernizr</a></li>
			<li><a href="http://www.php.net/" target="_blank">PHP</a></li>
			<li><a href="http://luracast.com/products/restler" target="_blank">Restler</a></li>
			<li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
		</ul>
	</li>
	<li>
		<a href="http://www.supportyourlocalclub.com/" target="_blank">Support Your Local Club</a>
		<p>A site for locating local professional and semi-pro soccer teams in the United States and Canada.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="http://ellislab.com/codeigniter" target="_blank">CodeIgniter</a></li>
			<li><a href="http://www.php.net/" target="_blank">PHP</a></li>
			<li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
			<li><a href="http://wordpress.org/" target="_blank">WordPress</a></li>
			<li><a href="https://developers.google.com/maps/documentation/javascript/" target="_blank">Google Maps JavaScript API</a></li>
		</ul>
	</li>
	<li>
		<a href="http://www.kevinjoseph.net/">KevinJoseph.net</a>
		<p>The site you're viewing.</p>
		<p>Technologies used:</p>
		<ul>
			<li><a href="http://backbonejs.org/" target="_blank">backbone.js</a></li>
			<li><a href="http://handlebarsjs.com/" target="_blank">Handlebars</a></li>
			<li><a href="http://modernizr.com/" target="_blank">Modernizr</a></li>
			<li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
		</ul>
	</li>
		
</ul>
